### ISSUE TITLE
Suggestion for example fastcgi configuration file and "hello world"

### ISSUE THREAD

**Issue by ThePrez** [sitemule/ILEfastCGI#1]
For those new to configuring fastcgi, could this project include a small sample with a fastcgi configuration file and a simple "hello world"-style RPG program?

**Comment by NielsLiisberg** [comment]
My fault, I need to make a a link to where all the samples are - It is used in the ILEastic project, so it is transparent for the RPG developer if he/she writes RPG servlets based on FastCGI or just HTTP

Here it is:

https://github.com/sitemule/ILEastic/blob/master/examples/Fastcgi01.rpgle

**Comment by ThePrez** [comment]
Works for me. We can close this one
